### ISSUE TITLE
PyDviGui/DviGlViewer uses PyOpenGLng.Tools.Interval that doesn't exist

### ISSUE THREAD

**Issue by yourealwaysbe** [FabriceSalvaire/PyDVI#14]
When i try to run the sample DVI viewer i get:

```
Traceback (most recent call last):
  File "bin/dvi-gl-viewer", line 35, in <module>
    from PyDviGui.DviGlViewer import Application
  File "/home/matt/apps/pydvi/src/PyDVI/PyDviGui/DviGlViewer/__init__.py", line 27, in <module>
    from PyOpenGLng.Tools.Interval import IntervalInt2D
ImportError: No module named Interval
```

And it seems Interval doesn't exist in the github version of PyOpenGLng.  Apologies if i'm missing something.

**Comment by FabriceSalvaire** [comment]
I don't have time to update PyDVI for PyOpenGL changes, you have to clone an older version of PyOpenGL. Try Nov 3, 2014 or older (September). You can also provide a patch.

**Comment by yourealwaysbe** [comment]
Ok, no problem.  Thanks.
